services:
  eshopdb:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: EShopDb

  seq:
    image: datalust/seq:latest

  distributedcache:
    image: redis

  messagebus:
      image: rabbitmq:management

  identity:
    image: quay.io/keycloak/keycloak:24.0.3


  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: Bootstrapper/Api/Dockerfile

volumes:
  postgres_eshopdb:
  keycloak_data:

