services:
  eshopdb:
    image: postgres:16
    container_name: eshopdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: EShopDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_eshopdb:/var/lib/postgresql/data

  seq:
    container_name: seq
    restart: always
    environment:
       - ACCEPT_EULA=Y
       - SEQ_FIRSTRUN_ADMINPASSWORD=P@ssw0rd
    ports:
      - "5341:5341"
      - "9091:80"

  distributedcache:
    container_name: distributedcache
    restart: always
    ports:
      - "6379:6379"


  messagebus:
    container_name: messagebus
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: always
    ports:
     - "5672:5672"
     - "15672:15672"
 

  identity:
    container_name: identity
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=P@ssw0rd
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://eshopdb:5432/EshopDb?currentSchema=identity
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=postgres
    ports:
      - "9090:8080"
    restart: always
    command:
      - start-dev
    depends_on:
      - eshopdb

volumes:
  postgres_eshopdb:
